# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceId', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('deviceName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discard',
            fields=[
                ('discardId', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=50)),
                ('finished', models.CharField(max_length=50)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='device_home.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('lendId', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=50)),
                ('finished', models.CharField(max_length=50)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='device_home.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repairId', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=50)),
                ('finished', models.CharField(max_length=50)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='device_home.Device')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
